"""First migration

Revision ID: 321372d135df
Revises: 
Create Date: 2021-05-20 19:35:32.562743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321372d135df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type'),
    sa.UniqueConstraint('type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentTypes')
    # ### end Alembic commands ###
